Make container resources optional
runatlantis/helm-charts pull request #188
Opened 2022-09-16 13:07 UTC by hazim1093

We are seeing CPU throttling with atlantis because of the CPU limits. 
It would be nice to make the resources (requests & limits) optional, so they can be configured per use case

2022-09-16 16:32 UTC, lkysow requested changes

2022-09-16 16:32 UTC, lkysow commented on charts/atlantis/values.yaml
> +#     cpu: 100m
This is a breaking change. Please leave it as-is and then in your own values you can set them to `{}`

2022-09-16 16:45 UTC, lkysow reviewed
Wait, actually can't you just use:

```
resources: {}
```


?

2022-09-18 15:15 UTC, hazim1093 commented
Hi @lkysow, 

In our case, we just want to remove CPU limits, and provide the rest. Since having CPU limits is causing unnecessary throttling on Atlantis

2022-09-18 15:51 UTC, lkysow commented
So just set resources.limits.cpu to null. Have you tried that? You shouldn't need to change the default settings for everyone else. You should be able to override settings in your own config file.

2022-09-18 15:52 UTC, closed without merging

2022-09-19 09:06 UTC, hazim1093 commented
It is not possible to set it to null. Also, I believe it's not the standard practice to force certain resource requests as default values. Probably many if not all, must be having CPU throttling because of the limits.

2022-09-19 18:49 UTC, lkysow commented
```yaml
resources:
  limits:
    cpu: null
```

```
 helm template . -f test-values.yaml | grep resources -A 5                                                                                         ⎈ gke-1
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 1Gi
--
      resources:
        requests:
          # The biggest thing Atlantis stores is the Git repo when it checks it out.
          # It deletes the repo after the pull request is merged.
          storage: 5Gi
```

It unsets it in my testing.

2022-09-20 08:34 UTC, hazim1093 commented
I was trying directly in the chart files and it rendered a `cpu: null` 
Works fine with the external values.yaml, thanks 👍

2022-09-20 15:11 UTC, lkysow commented
Ahh. This has more info: https://helm.sh/docs/intro/using_helm/. See
customization.

On Tue., Sep. 20, 2022, 1:34 a.m. Hazim, ***@***.***> wrote:

> I was trying directly in the chart files and it rendered a cpu: null
> Works fine with the external values.yaml, thanks 👍
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/runatlantis/helm-charts/pull/188#issuecomment-1252022263>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAH4RPI5UJWCU4T4N7OEQBLV7FZLBANCNFSM6AAAAAAQOKFNVI>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>