Change bitbucket.org values to be more clear
runatlantis/helm-charts pull request #246
Opened 2023-01-05 18:01 UTC by Eddie4Frost

## what

Change values.yaml to provide better information about how to use bitbucket.org as repository

## why

The actual values cause confusion

2023-01-20 14:45 UTC, GenPage requested changes

2023-01-20 14:45 UTC, GenPage commented on charts/atlantis/values.yaml
> +# If using Bitbucket
Can we fix the wording here to match the clarification of Bitbucket Cloud

2023-01-20 15:08 UTC, eltonpadilha submitted a review, later dismissed

2023-04-27 19:47 UTC, GenPage approved these changes

2023-04-27 19:48 UTC, merged