Allow to specify nodePort for service
runatlantis/helm-charts pull request #70
Opened 2021-06-25 17:21 UTC by PiyushBhatewara

2021-06-28 23:18 UTC, lkysow requested changes

2021-06-28 23:18 UTC, lkysow commented on charts/atlantis/values.yaml
> +  nodePort:
```suggestion
  nodePort: null
```

2021-07-20 16:48 UTC, PiyushBhatewara commented
All suggested changes are accepted. 

Please review.

2021-11-09 21:11 UTC, lkysow commented
Hi, please rebase I fixed the lint issue in main.

2022-04-14 16:24 UTC, closed without merging